name: ci

on: push

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20, 22]
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.after }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
      - name: Report Coverage
        if: ${{ matrix.node-version == 22 }}
        uses: qltysh/qlty-action/coverage@v1
        with:
          token: ${{ secrets.CC_TEST_REPORTER_ID }}
          files: coverage/lcov.info
