name: release

on: # Triggered by completed runs of the ci workflow on the main branch
  workflow_run:
    workflows:
      - "ci"
    branches:
      - main
    types:
      - completed

jobs:
  release:
    name: Test
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' # only on success
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm ci
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
